import 'dart:io';

import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import 'package:webview_flutter/webview_flutter.dart';

/// Displays a self-contained webmap HTML file (generated by WebMapGenerator)
/// via a file:// URI in a WebView. Includes a Share button to export the
/// .html file so it can be opened in a real browser.
class WebmapViewerScreen extends StatefulWidget {
  final File htmlFile;

  const WebmapViewerScreen({required this.htmlFile, super.key});

  @override
  State<WebmapViewerScreen> createState() => _WebmapViewerScreenState();
}

class _WebmapViewerScreenState extends State<WebmapViewerScreen> {
  late final WebViewController _controller;
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(Colors.white)
      ..enableZoom(true)
      ..setNavigationDelegate(
        NavigationDelegate(
          onPageFinished: (_) {
            if (mounted) setState(() => _loading = false);
          },
          onWebResourceError: (error) {
            debugPrint('WebView error: $error');
          },
        ),
      )
      ..loadFile(widget.htmlFile.path);
  }

  Future<void> _share() async {
    try {
      await Share.shareXFiles(
        [XFile(widget.htmlFile.path)],
        text: 'MapBanai WebMap',
        subject: 'MapBanai WebMap',
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Share failed: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('WebMap'),
        actions: [
          IconButton(
            icon: const Icon(Icons.share_outlined),
            tooltip: 'Share HTML file',
            onPressed: _share,
          ),
        ],
      ),
      body: Stack(
        children: [
          WebViewWidget(controller: _controller),
          if (_loading)
            const Center(child: CircularProgressIndicator()),
        ],
      ),
    );
  }
}
